// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test1.Data;

#nullable disable

namespace Test1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429122026_UpdateForCount")]
    partial class UpdateForCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Test1.Data.PlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoClickerAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoClickerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AutoClickerPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("AutoClickerStrength")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AutoClickerUpgradeCost")
                        .HasColumnType("REAL");

                    b.Property<int>("ClickMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickStrength")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClickUpgradeCost")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentCount")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
